### ISSUE TITLE
Users are registered with "wrong" name

### ISSUE THREAD

**Issue by dfreudenberger** [huafu/hubot-gitter2#6]
Hi there,

when using gitter2 + hubot-auth, it's pretty inconvenient to assign roles to users. Since gitter is tightly coupled to github, I'd assume I can assign roles to github names, just like I highlight them by @name

Unfortunately you have to assign roles to the full name like "Daniel Freudenberger (dfreudenberger)" which feels wrong. I think it could be easily fixed by storing the user's login name instead of his fullname somewhere here https://github.com/huafu/hubot-gitter2/blob/develop/src/HubotGitter2Adapter.coffee#L229

Looking forward to your feedback

**Comment by huafu** [comment]
That's a long time I didn't drop an eye, but it sounds like hubot-auth should instead use `login`, or `id` instead of a name that can be changed. Thoughts?

**Comment by dfreudenberger** [comment]
I'd love to agree but I think chances are pretty limited on this. hubot-auth is one of the default modules in hubot and is widely adopted. I don't think they'll introduce a bc break, especially since hubot-auth is working great in combination with campfire..

**Comment by huafu** [comment]
Looks like I'll have to drop a deeper eye at that. I think I remember changing totally the github-auth because of some issue like that... The goal was to be able to recogninze users thanks to any part of their name.

I'll do the change as an option, which would be true by default. Or can you do a PR adding another env var for that option, like `HUBOT_GITTER2_NAME_IS_LOGIN` which when not set (or set to any truthy value), it is `true` and means the login is used as the name, but when set to `0`, `no`, `false` or `off` would do the same as what it is doing now? I'll really appreciate because I am so busy on other things those days...

**Comment by dfreudenberger** [comment]
Yep, I'll provide a pull request during the next few days. Thanks in advance
